
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'DbgModelCppLib.nuspec'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '2'
    patchVersion: '0'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

